title: Monte Delizioso
author: Daniele Sagnotti
email: danielesagnotti@aol.com
description: >
  I blog about data and visualizations

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: marvinvandyke
  url: https://github.com/marvinvandyke
  icon: icon-github.svg
- username: Daniele Sagnotti
  url: https://www.linkedin.com/in/daniele-sagnotti-b2527392/
  icon: linkedin-icon-2.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
