# Site settings
title: Monte Delizioso
author:
  name: Daniele Sagnotti
  email: danielesagnotti@aol.com
description: "I blog about data and visualizations related to various topics from cooking to software development"

# Build settings
remote_theme: jekyll/minima
