# Site settings
title: Monte Delizioso
author:
  name: Daniele Sagnotti
  email: danielesagnotti@aol.com
description: I blog about data and visualizations related to various topics from cooking to software development

minima:
# generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
